FROM nkoshell/tle-storage-service:1.0.0
MAINTAINER nkoshell <nikita.koshelev@gmail.com>

WORKDIR /opt/tle-storage-service/

ONBUILD COPY requirements.txt ./
ONBUILD RUN pip install --no-cache -r requirements.txt

ONBUILD ADD . ./

ONBUILD ENTRYPOINT python -m app
