version: "2"

services:
  backend:
    build:
      context: ./backend
    environment:
      - DB_USER=tle_service_user
      - DB_PASSWORD=tle_service_user
      - DB_NAME=tle_service
    expose:
      - 8080
    image: tle_storage_service_backend:latest
    restart: always
    links:
      - postgres:db
  db:
    build:
      context: ./postgres
    ports:
      - 5432:5432
  frontend:
    build:
      context: .
    links:
      - backend
    ports:
      - 8080:80
